### ISSUE TITLE
Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by ilijab1** [Streamers-Workshop/Blazebot#229]
**When I start blazebot i got this error message:**

C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at navigate (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:108:47)
    at FrameManager.navigateFrame (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:13)
    at Frame.goto (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:417:41)
    at Page.goto (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:803:53)
    at Client.login (C:\Users\Ilija\Desktop\kajmak\Blazebot-master\node_modules\trovo.js\lib\client\BrowserClient.js:125:21)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by ilijab1** [comment]
FIX: check your settings.json file and make sure that the web address is correct. It should be in the format: https://trovo.live/channelName Alternatively, it could be poor internet connection or issue with the site, so retrying might work.
